apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: sonarqube-vm
  title: SonarQube VM
  description: SonarQube (formerly Sonar) is an open-source platform developed by SonarSource for continuous inspection of code quality to perform automatic reviews with static analysis of code to detect bugs, code smells, and security vulnerabilities on 20+ programming languages. SonarQube offers reports on duplicated code, coding standards, unit tests, code coverage, code complexity, comments, bugs, and security vulnerabilities.
  tags:
    - azure
    - environment

spec:
  owner: group:backstage-admins
  type: service
  parameters:
    - title: New Sonar Qube instance
      description: Options for creating the instance
      type: object
      required:
        - sonarqubePassword
      properties:
        sonarqubePassword:
          name: SonarQube Password
          type: string
          required: true
  steps:
    - id: fetch-deploy
      name: Fetch Deploy
      action: fetch:plain
      input:
        url: ./
        targetPath: ./deploy

    - id: debug-log
      name: Debug Log
      action: debug:log
      input:
        message: Hello World
        listWorkspace: true
